# This is a basic workflow to help you get started with Actions

name: Develop Branch CI

# Controls when the action will run. 
# Triggers the workflow on push request
on:
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: '14.0.1'
    - name: Build
      run: bash ./gradlew build --stacktrace
